name: Daily GitHub Activity

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update activity log
        run: |
          echo "✅ Daily ping: $(date)" >> activity_log.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "Becky0x01"
          git config --global user.email "your-email@example.com"
          git add .
          git commit -m "📅 Daily ping: $(date)"
          git push
